version: '2'
services:
  balanced-scale:
    build: .
    depends_on:
      - mongo
    ports:
      - "1337:1337"
    volumes:
      - .:/usr/src/app
    environment:
      MONGOLAB_URI: "mongodb://mongo:27017/balancedscale/"
      USERNAME: "boz@protonmail.com"
      PASSWORD: "d2igSnug"
    working_dir: "/usr/src/app"
    entrypoint: forever -w app.js 

  mongo:
    image: mongo:3.3
    ports:
      - "27018:27017"

